In [1]:
# This block was generated by default by kaggle 
# The below code just lists all the files from dataset folder
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# The output path of this cell , can be used as Data path when reading the csv.

/kaggle/input/datasets/gagandeep16/car-sales/Car_sales.csv

# Introduction
### Car Sales Data Cleaning & Analysis

- This notebook explores the Car Sales dataset using Pandas. 
- The goal is to clean and prepare the data so it is consistent, structured, and ready for analysis.
- I have tried my best to keep my work in its simplest form for all levels of data analysts.
- Refer to Table of contents for smoother navigation.

# Preparation for Data Cleaning
- Load required libraries
- Load the data

In [2]:
# Import required libraries for data analysis.
import numpy as np
import pandas as pd

In [3]:
# Load the Cars Data set
Cars = pd.read_csv("/kaggle/input/datasets/gagandeep16/car-sales/Car_sales.csv")

# Data Inspection
- Check first and last records
- Inspect Sample rows
- Understanding the columns and getting familiarized with data
- Shape of data
- Checking Data types of each column

In [4]:
# Display first 5 rows
Cars.head(5)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [5]:
# Display last 5 rows 
Cars.tail(5)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
152,Volvo,V40,3.545,NaN,Passenger,24.4,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.0,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [6]:
# Display sample rows
Cars.sample(10)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
31,Chrysler,Cirrus,32.306,12.640,Passenger,16.480,2.0,132.0,108.0,71.0,186.0,2.911,16.0,27.0,10/6/2011,53.566200
155,Volvo,C70,3.493,NaN,Passenger,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
140,Toyota,Tacoma,84.087,9.575,Car,11.528,2.4,142.0,103.3,66.5,178.7,2.580,15.1,23.0,8/1/2011,55.297117
61,Honda,Odyssey,76.029,19.490,Car,26.000,3.5,210.0,118.1,75.6,201.2,4.288,20.0,23.0,2/8/2012,85.217691
100,Mercedes-B,M-Class,28.976,NaN,Car,35.300,3.2,215.0,111.0,72.2,180.6,4.387,19.0,20.0,2/10/2011,90.495532
68,Jeep,Cherokee,80.556,13.775,Car,21.620,4.0,190.0,101.4,69.4,167.5,3.194,20.0,20.0,10/5/2012,76.584440
26,Chevrolet,Metro,21.855,5.160,Passenger,9.235,1.0,55.0,93.1,62.6,149.4,1.895,10.3,45.0,4/13/2012,23.276272
103,Nissan,Maxima,79.853,15.125,Passenger,26.249,3.0,222.0,108.3,70.3,190.5,3.294,18.5,25.0,5/6/2011,89.427820
81,Mitsubishi,Galant,55.616,10.595,Passenger,17.357,2.4,145.0,103.7,68.5,187.8,2.945,16.3,25.0,1/29/2012,58.606773
16,Cadillac,Eldorado,6.536,25.725,Passenger,39.665,4.6,275.0,108.0,75.5,200.6,3.843,19.0,22.0,11/27/2011,113.765874

In [7]:
# Display the column names
Cars.columns

Index(['Manufacturer', 'Model', 'Sales_in_thousands', '__year_resale_value',
       'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb_weight', 'Fuel_capacity',
       'Fuel_efficiency', 'Latest_Launch', 'Power_perf_factor'],
      dtype='object')

In [8]:
# Display the Data type of each column
Cars.dtypes

Manufacturer            object
Model                   object
Sales_in_thousands     float64
__year_resale_value    float64
Vehicle_type            object
Price_in_thousands     float64
Engine_size            float64
Horsepower             float64
Wheelbase              float64
Width                  float64
Length                 float64
Curb_weight            float64
Fuel_capacity          float64
Fuel_efficiency        float64
Latest_Launch           object
Power_perf_factor      float64
dtype: object

In [9]:
# Check Column names , Non-null count and Datatypes
Cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    object
 1   Model                157 non-null    object
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    object
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    object
 15  Power_perf_factor    155 non-null    float64
dtypes: float64(12), object(4)
memory usage: 19.8+ KB

In [10]:
# Understanding the shape of data
Cars.shape

(157, 16)

In [11]:
# Calculate basic statistics for every column
Cars.describe().round(1)

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor
count,157.0,121.0,155.0,156.0,156.0,156.0,156.0,156.0,155.0,156.0,154.0,155.0
mean,53.0,18.1,27.4,3.1,185.9,107.5,71.2,187.3,3.4,18.0,23.8,77.0
std,68.0,11.5,14.4,1.0,56.7,7.6,3.5,13.4,0.6,3.9,4.3,25.1
min,0.1,5.2,9.2,1.0,55.0,92.6,62.6,149.4,1.9,10.3,15.0,23.3
25%,14.1,11.3,18.0,2.3,149.5,103.0,68.4,177.6,3.0,15.8,21.0,60.4
50%,29.4,14.2,22.8,3.0,177.5,107.0,70.6,187.9,3.3,17.2,24.0,72.0
75%,68.0,19.9,31.9,3.6,215.0,112.2,73.4,196.1,3.8,19.6,26.0,89.4
max,540.6,67.6,85.5,8.0,450.0,138.7,79.9,224.5,5.6,32.0,45.0,188.1

# Fix column headers
- Convert to lower case and remove spaces
- Rename column names
- Fix data types

In [ ]:
# Remove spaces , lower case from all column headers.  
Cars.columns = (
    Cars.columns
    .str.strip()
    .str.lower()
)

In [13]:
# Check whether column headers got fixed
Cars.columns

Index(['manufacturer', 'model', 'sales_in_thousands', '__year_resale_value',
       'vehicle_type', 'price_in_thousands', 'engine_size', 'horsepower',
       'wheelbase', 'width', 'length', 'curb_weight', 'fuel_capacity',
       'fuel_efficiency', 'latest_launch', 'power_perf_factor'],
      dtype='object')

In [14]:
# Rename Column headers
Cars = Cars.rename(columns = {
    'sales_in_thousands':'sales',
    '__year_resale_value':'year_resale_value',
    'price_in_thousands':'price'
})

In [15]:
# Check column names
Cars.columns

Index(['manufacturer', 'model', 'sales', 'year_resale_value', 'vehicle_type',
       'price', 'engine_size', 'horsepower', 'wheelbase', 'width', 'length',
       'curb_weight', 'fuel_capacity', 'fuel_efficiency', 'latest_launch',
       'power_perf_factor'],
      dtype='object')

In [16]:
# Multiply price and sales column by 1000 to fix the values.
Cars['price'] = Cars['price']*1000
Cars['sales'] = Cars['sales']*1000

In [17]:
# Check whether price and values are fixed. 
Cars.loc[0:5,['manufacturer','model','price','sales']]

  manufacturer    model    price    sales
0        Acura  Integra  21500.0  16919.0
1        Acura       TL  28400.0  39384.0
2        Acura       CL      NaN  14114.0
3        Acura       RL  42000.0   8588.0
4         Audi       A4  23990.0  20397.0
5         Audi       A6  33950.0  18780.0

# Fix Data types of column
- Check data types of each column
- Change the data types of required columns

In [18]:
Cars.dtypes

manufacturer          object
model                 object
sales                float64
year_resale_value    float64
vehicle_type          object
price                float64
engine_size          float64
horsepower           float64
wheelbase            float64
width                float64
length               float64
curb_weight          float64
fuel_capacity        float64
fuel_efficiency      float64
latest_launch         object
power_perf_factor    float64
dtype: object

### Data Types

- **manufacturer (object)**: Contains text values representing brand names. Object type is appropriate.
- **model (object)**: Contains text values for car models. Object type is suitable.
- **sales (float64)**: Numeric column representing number of units sold. Float is acceptable for calculations and analysis.
- **year_resale_value (float64)**: Numeric values representing resale value. Float type is appropriate for handling missing values and decimals.
- **vehicle_type (object)**: Categorical text data (e.g., passenger, SUV). Object type is suitable.
- **price (float64)**: Numeric column representing car price. Float is appropriate for calculations and comparisons.
- **engine_size (float64)**: Numeric measurement of engine capacity. Float type is suitable.
- **horsepower (float64)**: Numeric performance metric. Float type is appropriate.
- **wheelbase (float64)**: Numeric measurement of vehicle dimensions. Float is suitable.
- **width (float64)**: Numeric column representing car width. Float is appropriate.
- **length (float64)**: Numeric column representing car length. Float is appropriate.
- **curb_weight (float64)**: Numeric value representing vehicle weight. Float type is suitable.
- **fuel_capacity (float64)**: Numeric measurement of fuel tank capacity. Float is appropriate.
- **fuel_efficiency (float64)**: Numeric value representing efficiency. Float is suitable for analysis.
- **latest_launch (object → datetime)**: Currently stored as object but represents dates. Should be converted to datetime for proper time-based analysis.
- **power_perf_factor (float64)**: Numeric performance-related metric. Float type is appropriate.

In [19]:
# Convert data type of latest_launch from object to datetime
Cars['latest_launch'] = pd.to_datetime(Cars['latest_launch'])

In [20]:
Cars.dtypes

manufacturer                 object
model                        object
sales                       float64
year_resale_value           float64
vehicle_type                 object
price                       float64
engine_size                 float64
horsepower                  float64
wheelbase                   float64
width                       float64
length                      float64
curb_weight                 float64
fuel_capacity               float64
fuel_efficiency             float64
latest_launch        datetime64[ns]
power_perf_factor           float64
dtype: object

# Detecting Nulls
- We will count nulls for each column
- Data Imputation

In [21]:
Cars.isnull().sum()

manufacturer          0
model                 0
sales                 0
year_resale_value    36
vehicle_type          0
price                 2
engine_size           1
horsepower            1
wheelbase             1
width                 1
length                1
curb_weight           2
fuel_capacity         1
fuel_efficiency       3
latest_launch         0
power_perf_factor     2
dtype: int64

In [22]:
# Show rows where year_resale_value is null 
((Cars.isnull().sum() / len(Cars)) * 100).round(1)

manufacturer          0.0
model                 0.0
sales                 0.0
year_resale_value    22.9
vehicle_type          0.0
price                 1.3
engine_size           0.6
horsepower            0.6
wheelbase             0.6
width                 0.6
length                0.6
curb_weight           1.3
fuel_capacity         0.6
fuel_efficiency       1.9
latest_launch         0.0
power_perf_factor     1.3
dtype: float64

In [23]:
# Fill the columns with mean()
cols = ['price', 'engine_size', 'horsepower', 'wheelbase', 'width',
        'length', 'curb_weight', 'fuel_capacity', 'fuel_efficiency',
        'power_perf_factor']

for col in cols:
    Cars[col] = Cars[col].fillna(Cars[col].mean())

In [24]:
# Filling with medians in year_resale_value column
Cars['year_resale_value'] = Cars['year_resale_value'].fillna(Cars['year_resale_value'].median())

In [25]:
# Checking the count of nulls 
Cars.isnull().sum()

manufacturer         0
model                0
sales                0
year_resale_value    0
vehicle_type         0
price                0
engine_size          0
horsepower           0
wheelbase            0
width                0
length               0
curb_weight          0
fuel_capacity        0
fuel_efficiency      0
latest_launch        0
power_perf_factor    0
dtype: int64

# Fixing Duplicates 
- Detecting duplicates
- Dropping duplicate records

In [26]:
# Check duplicates
Cars.duplicated().sum()

np.int64(0)

In [27]:
# Display duplicated rows
Cars[Cars.duplicated()]

Empty DataFrame
Columns: [manufacturer, model, sales, year_resale_value, vehicle_type, price, engine_size, horsepower, wheelbase, width, length, curb_weight, fuel_capacity, fuel_efficiency, latest_launch, power_perf_factor]
Index: []

In [28]:
# Saving the cleaned file.
Cars.to_csv("/kaggle/working/cleaned_car_sales.csv", index=False)

# Conclusion

In this notebook, the Car Sales dataset was cleaned and prepared for analysis. Column names were standardized, data types were verified, missing values were handled, and duplicates were checked.

The dataset is now consistent and ready for further analysis and visualization. This forms a solid foundation for exploring patterns such as sales trends, pricing, and vehicle characteristics.